// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls=WPAppStudio.Controls;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using IServices=WPAppStudio.Services.Interfaces;
using IViewModels=WPAppStudio.ViewModel.Interfaces;
using Localization=WPAppStudio.Localization;
using Repositories=WPAppStudio.Repositories;
using Services=WPAppStudio.Services;
using ViewModelsBase=WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of characters_Detail ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class characters_DetailViewModel : ViewModelsBase.VMBase, IViewModels.Icharacters_DetailViewModel, ViewModelsBase.INavigable
    {       

		private readonly Repositories.characters_charactersCollection _characters_charactersCollection;
		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ISpeechService _speechService;
		private readonly IServices.IShareService _shareService;
		private readonly IServices.ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="characters_DetailViewModel" /> class.
        /// </summary>
        /// <param name="characters_charactersCollection">The Characters_characters Collection.</param>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public characters_DetailViewModel(Repositories.characters_charactersCollection characters_charactersCollection, IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ISpeechService speechService, IServices.IShareService shareService, IServices.ILiveTileService liveTileService)
        {
			_characters_charactersCollection = characters_charactersCollection;
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		
	
		private Entities.charactersSchema _currentcharactersSchema;

        /// <summary>
        /// CurrentcharactersSchema property.
        /// </summary>		
        public Entities.charactersSchema CurrentcharactersSchema
        {
            get
            {
				return _currentcharactersSchema;
            }
            set
            {
                SetProperty(ref _currentcharactersSchema, value);
            }
        }
	
		private bool _hasNextpanoramacharacters_Detail0;

        /// <summary>
        /// HasNextpanoramacharacters_Detail0 property.
        /// </summary>		
        public bool HasNextpanoramacharacters_Detail0
        {
            get
            {
				return _hasNextpanoramacharacters_Detail0;
            }
            set
            {
                SetProperty(ref _hasNextpanoramacharacters_Detail0, value);
            }
        }
	
		private bool _hasPreviouspanoramacharacters_Detail0;

        /// <summary>
        /// HasPreviouspanoramacharacters_Detail0 property.
        /// </summary>		
        public bool HasPreviouspanoramacharacters_Detail0
        {
            get
            {
				return _hasPreviouspanoramacharacters_Detail0;
            }
            set
            {
                SetProperty(ref _hasPreviouspanoramacharacters_Detail0, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechcharacters_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechcharacters_DetailStaticControlCommandDelegate() 
        {
				_speechService.TextToSpeech(CurrentcharactersSchema.Subtitle + " " + CurrentcharactersSchema.Description);
        }
		

        private ICommand _textToSpeechcharacters_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechcharacters_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechcharacters_DetailStaticControlCommand
        {
            get { return _textToSpeechcharacters_DetailStaticControlCommand = _textToSpeechcharacters_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(TextToSpeechcharacters_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Sharecharacters_DetailStaticControlCommand command.
        /// </summary>
        public  void Sharecharacters_DetailStaticControlCommandDelegate() 
        {
				_shareService.Share(CurrentcharactersSchema.Subtitle, CurrentcharactersSchema.Description, "", CurrentcharactersSchema.Image);
        }
		

        private ICommand _sharecharacters_DetailStaticControlCommand;

        /// <summary>
        /// Gets the Sharecharacters_DetailStaticControlCommand command.
        /// </summary>
        public ICommand Sharecharacters_DetailStaticControlCommand
        {
            get { return _sharecharacters_DetailStaticControlCommand = _sharecharacters_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(Sharecharacters_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartcharacters_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartcharacters_DetailStaticControlCommandDelegate() 
        {
				_liveTileService.PinToStart(typeof(IViewModels.Icharacters_DetailViewModel), CreateTileInfocharacters_DetailStaticControl());
        }
		

        private ICommand _pinToStartcharacters_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartcharacters_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartcharacters_DetailStaticControlCommand
        {
            get { return _pinToStartcharacters_DetailStaticControlCommand = _pinToStartcharacters_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(PinToStartcharacters_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Nextpanoramacharacters_Detail0 command.
        /// </summary>
        public  void Nextpanoramacharacters_Detail0Delegate() 
        {
			var next =  _characters_charactersCollection.Next(CurrentcharactersSchema);

			if(next != null)
				CurrentcharactersSchema = next;

			RefreshHasPrevNext();
        }
		

        private ICommand _nextpanoramacharacters_Detail0;

        /// <summary>
        /// Gets the Nextpanoramacharacters_Detail0 command.
        /// </summary>
        public ICommand Nextpanoramacharacters_Detail0
        {
            get { return _nextpanoramacharacters_Detail0 = _nextpanoramacharacters_Detail0 ?? new ViewModelsBase.DelegateCommand(Nextpanoramacharacters_Detail0Delegate); }
        }

        /// <summary>
        /// Delegate method for the Previouspanoramacharacters_Detail0 command.
        /// </summary>
        public  void Previouspanoramacharacters_Detail0Delegate() 
        {
			var prev =  _characters_charactersCollection.Previous(CurrentcharactersSchema);

			if(prev != null)
				CurrentcharactersSchema = prev;

			RefreshHasPrevNext();
        }
		

        private ICommand _previouspanoramacharacters_Detail0;

        /// <summary>
        /// Gets the Previouspanoramacharacters_Detail0 command.
        /// </summary>
        public ICommand Previouspanoramacharacters_Detail0
        {
            get { return _previouspanoramacharacters_Detail0 = _previouspanoramacharacters_Detail0 ?? new ViewModelsBase.DelegateCommand(Previouspanoramacharacters_Detail0Delegate); }
        }

        private void RefreshHasPrevNext()
        {
            HasPreviouspanoramacharacters_Detail0 = _characters_charactersCollection.HasPrevious(CurrentcharactersSchema);
			HasNextpanoramacharacters_Detail0 = _characters_charactersCollection.HasNext(CurrentcharactersSchema);
		}
		public object NavigationContext
        {
            set
            {              
                if (!(value is Entities.charactersSchema)) { return; }
                
                CurrentcharactersSchema = value as Entities.charactersSchema;
                RefreshHasPrevNext();
            }
        }
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the characters_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfocharacters_DetailStaticControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = CurrentcharactersSchema.Id.ToString(),
                Title = CurrentcharactersSchema.Subtitle,
                BackTitle = CurrentcharactersSchema.Subtitle,
                BackContent = CurrentcharactersSchema.Description,
                Count = 0,
                BackgroundImagePath = CurrentcharactersSchema.Image,
                BackBackgroundImagePath = CurrentcharactersSchema.Image,
                LogoPath = "Logo-2304ce0a-3c98-453b-bb1b-5a0077d14161.png"
            };
            return tileInfo;
        }
    }
}
