// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls=WPAppStudio.Controls;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using IServices=WPAppStudio.Services.Interfaces;
using IViewModels=WPAppStudio.ViewModel.Interfaces;
using Localization=WPAppStudio.Localization;
using Repositories=WPAppStudio.Repositories;
using Services=WPAppStudio.Services;
using ViewModelsBase=WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of pictures_Manga ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class pictures_MangaViewModel : ViewModelsBase.VMBase, IViewModels.Ipictures_MangaViewModel
    {       

		private readonly IServices.IDialogService _dialogService;
		private readonly Repositories.Ipictures_picturesDataSource _pictures_picturesDataSource;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="pictures_MangaViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="pictures_picturesDataSource">The Pictures_pictures Data Source.</param>
        public pictures_MangaViewModel(IServices.IDialogService dialogService, Repositories.Ipictures_picturesDataSource pictures_picturesDataSource)
        {
			_dialogService = dialogService;
			_pictures_picturesDataSource = pictures_picturesDataSource;
        }
		
	
		private ObservableCollection<EntitiesBase.RssSearchResult> _pictures_MangaListControlCollection;

        /// <summary>
        /// Pictures_MangaListControlCollection property.
        /// </summary>		
        public ObservableCollection<EntitiesBase.RssSearchResult> Pictures_MangaListControlCollection
        {
            get
            {
				
                if(_pictures_MangaListControlCollection == null)
					Getpictures_MangaListControlCollectionData();
				return _pictures_MangaListControlCollection;     
            }
            set
            {
                SetProperty(ref _pictures_MangaListControlCollection, value);
            }
        }
	
		private EntitiesBase.RssSearchResult _selectedpictures_MangaListControlCollection;

        /// <summary>
        /// Selectedpictures_MangaListControlCollection property.
        /// </summary>		
        public EntitiesBase.RssSearchResult Selectedpictures_MangaListControlCollection
        {
            get
            {
				return _selectedpictures_MangaListControlCollection;
            }
            set
            {
                SetProperty(ref _selectedpictures_MangaListControlCollection, value);
            }
        }

        /// <summary>
        /// Delegate method for the Refreshpictures_MangaListControlCollectionCommand command.
        /// </summary>
        public async void Refreshpictures_MangaListControlCollectionCommandDelegate() 
        {
			try
			{
				LoadingPictures_MangaListControlCollection = true;
				var items = await  _pictures_picturesDataSource.Refresh();
				Pictures_MangaListControlCollection = items;
			}
            catch (Exception ex)
            {
				Pictures_MangaListControlCollection = null;
		
                Debug.WriteLine(ex.ToString());
                _dialogService.Show(Localization.AppResources.rssError + Environment.NewLine + Localization.AppResources.TryAgain);
            }
            finally
            {
				LoadingPictures_MangaListControlCollection = false;
			}
        }
		
		
        private bool _loadingPictures_MangaListControlCollection;
		
        public bool LoadingPictures_MangaListControlCollection
        {
            get { return _loadingPictures_MangaListControlCollection; }
            set { SetProperty(ref _loadingPictures_MangaListControlCollection, value); }
        }

        private ICommand _refreshpictures_MangaListControlCollectionCommand;

        /// <summary>
        /// Gets the Refreshpictures_MangaListControlCollectionCommand command.
        /// </summary>
        public ICommand Refreshpictures_MangaListControlCollectionCommand
        {
            get { return _refreshpictures_MangaListControlCollectionCommand = _refreshpictures_MangaListControlCollectionCommand ?? new ViewModelsBase.DelegateCommand(Refreshpictures_MangaListControlCollectionCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Getpictures_MangaListControlCollectionCommand command.
        /// </summary>
        public  void Getpictures_MangaListControlCollectionCommandDelegate(int pageNumber= 0) 
        {
				Getpictures_MangaListControlCollectionData(pageNumber);
        }
		

        private ICommand _getpictures_MangaListControlCollectionCommand;

        /// <summary>
        /// Gets the Getpictures_MangaListControlCollectionCommand command.
        /// </summary>
        public ICommand Getpictures_MangaListControlCollectionCommand
        {
            get { return _getpictures_MangaListControlCollectionCommand = _getpictures_MangaListControlCollectionCommand ?? new ViewModelsBase.DelegateCommand<int>(Getpictures_MangaListControlCollectionCommandDelegate); }
        }

        private async void Getpictures_MangaListControlCollectionData(int pageNumber = 0)
        {
	
			try
			{
				LoadingPictures_MangaListControlCollection = true;
			
				var items = await _pictures_picturesDataSource.GetData();
                Pictures_MangaListControlCollection = items;
			}
            catch (Exception ex)
            {
				Pictures_MangaListControlCollection = null;
		
                Debug.WriteLine(ex.ToString());
                _dialogService.Show(Localization.AppResources.rssError + Environment.NewLine + Localization.AppResources.TryAgain);
            }
            finally
            {
				LoadingPictures_MangaListControlCollection = false;
			}
		}
    }
}
