// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// characters_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface Icharacters_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentcharactersSchema property.
        /// </summary>
		Entities.charactersSchema CurrentcharactersSchema { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramacharacters_Detail0 property.
        /// </summary>
		bool HasNextpanoramacharacters_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramacharacters_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramacharacters_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechcharacters_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechcharacters_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Sharecharacters_DetailStaticControlCommand command.
        /// </summary>
		ICommand Sharecharacters_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartcharacters_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartcharacters_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Nextpanoramacharacters_Detail0 command.
        /// </summary>
		ICommand Nextpanoramacharacters_Detail0 { get; }

        
        /// <summary>
        /// Gets the Previouspanoramacharacters_Detail0 command.
        /// </summary>
		ICommand Previouspanoramacharacters_Detail0 { get; }

	}
}
