// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// characters_List ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface Icharacters_ListViewModel
    {		
        /// <summary>
        /// Gets/Sets the Characters_ListListControlCollection property.
        /// </summary>
		ObservableCollection<Entities.charactersSchema> Characters_ListListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the Characters_ListListControlCollectionPageNumber property.
        /// </summary>
		int Characters_ListListControlCollectionPageNumber { get; set; }
        /// <summary>
        /// Gets/Sets the Selectedcharacters_ListListControlCollection property.
        /// </summary>
		Entities.charactersSchema Selectedcharacters_ListListControlCollection { get; set; }
        
        /// <summary>
        /// Gets the Getcharacters_ListListControlCollectionCommand command.
        /// </summary>
		ICommand Getcharacters_ListListControlCollectionCommand { get; }

	}
}
