// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Movie_DetailVideos ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IMovie_DetailVideosViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentYouTubeVideo property.
        /// </summary>
		EntitiesBase.YouTubeVideo CurrentYouTubeVideo { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaMovie_DetailVideos0 property.
        /// </summary>
		bool HasNextpanoramaMovie_DetailVideos0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaMovie_DetailVideos0 property.
        /// </summary>
		bool HasPreviouspanoramaMovie_DetailVideos0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechMovie_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechMovie_DetailVideosStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareMovie_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand ShareMovie_DetailVideosStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartMovie_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand PinToStartMovie_DetailVideosStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceMovie_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceMovie_DetailVideosStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaMovie_DetailVideos0 command.
        /// </summary>
		ICommand NextpanoramaMovie_DetailVideos0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaMovie_DetailVideos0 command.
        /// </summary>
		ICommand PreviouspanoramaMovie_DetailVideos0 { get; }

	}
}
