// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// TheStory_Info ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface ITheStory_InfoViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentTheStory_InfoHtmlControl property.
        /// </summary>
		string CurrentTheStory_InfoHtmlControl { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechTheStory_InfoHtmlControlCommand command.
        /// </summary>
		ICommand TextToSpeechTheStory_InfoHtmlControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareTheStory_InfoHtmlControlCommand command.
        /// </summary>
		ICommand ShareTheStory_InfoHtmlControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartTheStory_InfoHtmlControlCommand command.
        /// </summary>
		ICommand PinToStartTheStory_InfoHtmlControlCommand { get; }

	}
}
