// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;
using Entities=WPAppStudio.Entities;
using RepositoriesBase=WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// TheStoryDataSource_Html data source.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class TheStory_TheStoryDataSource : ITheStory_TheStoryDataSource 
    {        
        /// <summary>
        /// Retrieves the html content.
        /// </summary>
        /// <returns>A string with the content in html format.</returns>
        public string Get()
        {			
            return @"<b>วันพีซเป็นหนึ่งในการ์ตูนที่โด่งดังที่สุดของญี่ปุ่น จุดเด่นของเรื่องนี้อยู่ที่การที่ผู้วาดได้สร้างสรรค์ความฝันซึ่งต้องการผจญภัยพร้อมกับเหล่ามิตรแท้ในวัยเด็กของหลาย ๆ คนได้อย่างมีเสน่ห์ โดยระหว่างการผจญภัย ลูฟี่ต้องเจออุปสรรคในการพิสูจน์เพื่อนแท้มากมาย รวมทั้งได้เรียนรู้เรื่องราวและตำนานของบุคคลต่าง ๆ ที่ผ่านเข้ามาในเนื้อเรื่อง ไม่ว่าจะเป็น</b><a rel=""nofollow"" target=""_blank"" href=""http://th.wikipedia.org/wiki/%E0%B8%81%E0%B8%AD%E0%B8%87%E0%B8%97%E0%B8%B1%E0%B8%9E%E0%B9%80%E0%B8%A3%E0%B8%B7%E0%B8%AD_(%E0%B8%A7%E0%B8%B1%E0%B8%99%E0%B8%9E%E0%B8%B5%E0%B8%8B)"" title=""Link: http://th.wikipedia.org/wiki/%E0%B8%81%E0%B8%AD%E0%B8%87%E0%B8%97%E0%B8%B1%E0%B8%9E%E0%B9%80%E0%B8%A3%E0%B8%B7%E0%B8%AD_(%E0%B8%A7%E0%B8%B1%E0%B8%99%E0%B8%9E%E0%B8%B5%E0%B8%8B)""><b>กองทัพเรือ</b></a><b>ของ</b><a rel=""nofollow"" target=""_blank"" href=""http://th.wikipedia.org/wiki/%E0%B8%A3%E0%B8%B1%E0%B8%90%E0%B8%9A%E0%B8%B2%E0%B8%A5%E0%B9%82%E0%B8%A5%E0%B8%81""><b>รัฐบาลโลก</b></a><a rel=""nofollow"" target=""_blank"" href=""http://th.wikipedia.org/wiki/%E0%B9%80%E0%B8%88%E0%B9%87%E0%B8%94%E0%B9%80%E0%B8%97%E0%B8%9E%E0%B9%82%E0%B8%88%E0%B8%A3%E0%B8%AA%E0%B8%A5%E0%B8%B1%E0%B8%94""><b>เจ็ดเทพโจรสลัด</b></a><b>เจ้าหญิงวีวี่แห่งอาลาบัสต้า เมืองแห่งทะเลทราย โนแลนด์จอมโกหก และเกาะแห่งท้องฟ้าในตำนาน</b><br />";
        }
	}
}

