// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   UnityContainer.tt
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using IIoc=WPAppStudio.Ioc.Interfaces;
using IServices=WPAppStudio.Services.Interfaces;
using IViewModels=WPAppStudio.ViewModel.Interfaces;
using Microsoft.Practices.Unity;
using Repositories=WPAppStudio.Repositories;
using RepositoriesBase=WPAppStudio.Repositories.Base;
using Services=WPAppStudio.Services;
using ViewModels=WPAppStudio.ViewModel;

namespace WPAppStudio.Ioc
{
    //
    // Unity 2.1
    // http://msdn.microsoft.com/en-us/library/hh237493.aspx
    //
    // patterns & practices - Unity
    // http://unity.codeplex.com/
    //
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class Container : IIoc.IContainer
    {
        private readonly IUnityContainer _currentContainer;

        public Container()
        {
            _currentContainer = new UnityContainer();

            _currentContainer.RegisterType<IServices.ILiveTileService, Services.LiveTileService>();
			_currentContainer.RegisterType<IServices.ILockScreenService, Services.LockScreenService>();
			_currentContainer.RegisterType<IServices.IProximityService, Services.ProximityService>();
            _currentContainer.RegisterType<IServices.IDialogService, Services.DialogService>();
            _currentContainer.RegisterType<IServices.IShareService, Services.ShareService>();
			
            _currentContainer.RegisterType<IServices.ISpeechService, Services.SpeechService>();
            _currentContainer.RegisterType<IServices.INavigationService, Services.NavigationService>();
			
		
		    _currentContainer.RegisterType<IServices.IStorageService, Services.StorageService>();
			_currentContainer.RegisterType<IServices.IInternetService, Services.InternetService>(new ContainerControlledLifetimeManager());
			_currentContainer.RegisterType<RepositoriesBase.IXmlDataSource, RepositoriesBase.XmlDataSource>();
			_currentContainer.RegisterType<RepositoriesBase.IYoutubeDataSource, RepositoriesBase.YoutubeDataSource>();
            _currentContainer.RegisterType<IViewModels.Istart_LetsGoViewModel, ViewModels.start_LetsGoViewModel>();
            _currentContainer.RegisterType<IViewModels.IMovie_DetailVideosViewModel, ViewModels.Movie_DetailVideosViewModel>();
            _currentContainer.RegisterType<IViewModels.ITheStory_InfoViewModel, ViewModels.TheStory_InfoViewModel>();
            _currentContainer.RegisterType<IViewModels.Ipictures_MangaViewModel, ViewModels.pictures_MangaViewModel>();
            _currentContainer.RegisterType<IViewModels.Icharacters_ListViewModel, ViewModels.characters_ListViewModel>();
            _currentContainer.RegisterType<IViewModels.Icharacters_DetailViewModel, ViewModels.characters_DetailViewModel>();

			_currentContainer.RegisterType<IViewModels.IAboutViewModel, ViewModels.AboutViewModel>(new ContainerControlledLifetimeManager());
			_currentContainer.RegisterType<IViewModels.ILicenseViewModel, ViewModels.LicenseViewModel>(new ContainerControlledLifetimeManager());
			
			if (!System.ComponentModel.DesignerProperties.IsInDesignTool)
            {
				_currentContainer.RegisterType<Repositories.IMovie_Movie, Repositories.Movie_Movie>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.ITheStory_TheStoryDataSource, Repositories.TheStory_TheStoryDataSource>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.Ipictures_picturesDataSource, Repositories.pictures_picturesDataSource>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.Icharacters_charactersCollection, Repositories.characters_charactersCollection>(new ContainerControlledLifetimeManager());
			}
			else
			{
				_currentContainer.RegisterType<Repositories.IMovie_Movie, Repositories.FakeMovie_Movie>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.ITheStory_TheStoryDataSource, Repositories.FakeTheStory_TheStoryDataSource>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.Ipictures_picturesDataSource, Repositories.Fakepictures_picturesDataSource>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.Icharacters_charactersCollection, Repositories.Fakecharacters_charactersCollection>(new ContainerControlledLifetimeManager());
			
			}
        }

        public T Resolve<T>()
        {
            return _currentContainer.Resolve<T>();
        }
    }
}
